# template.sub
# starter submit file for CHTC jobs
getenv=true
universe = vanilla

executable = pnn.sh

log = pnn.log
error = pnn.err
output = pnn.out

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = ../../../test-env.tar.gz, ../../../warfarin.tar.gz, pnn.py
transfer_output_files = output.tar.gz

request_cpus = 4
request_memory = 32GB
request_disk = 8GB

notification = Always
notify_user = vmpatil@wisc.edu

queue 1